inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "core/vendor/**/*"
    - "core/.bundle/**/*"
    - "core/data/**/*"
    - "core/config/**/*"
    - "core/Gemfile.lock"
