inherit_gem:
  standard: config/base.yml

plugins:
  - rubocop-sequel

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "core/vendor/**/*"
    - "core/.bundle/**/*"
    - "core/data/**/*"
    - "core/config/**/*"
    - "core/Gemfile.lock"

# Disable cops that conflict with StandardRB
Style/StringLiterals:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

# Disable some metrics cops for existing code
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Enabled: false
