source "https://rubygems.org"

gem "thor"
gem "nitty_mail", path: "../gem"
gem "chroma-db"
gem "ruby-progressbar"
gem "reverse_markdown"
gem "mail"

group :development do
  gem "standard", ">= 1.35.1", require: false
  gem "rubocop", require: false
  gem "rspec", require: false
  gem "rspec-given", require: false
end
