source "https://rubygems.org"

gem "thor"
gem "nitty_mail", path: "../gem"
gem "ruby-progressbar"
gem "reverse_markdown"
gem "mail"
gem "activerecord", ">= 8.0", "< 9.0"
gem "sqlite3", ">= 2.1", "< 3.0"
gem "activesupport", ">= 8.0", "< 9.0"
gem "activejob", ">= 8.0", "< 9.0"
gem "redis", ">= 5.0"
gem "sidekiq", ">= 7.1"
gem "dotenv"
gem "rack" # Rack middleware/web
gem "rackup" # Provides the `rackup` executable in Rack 3
gem "rack-session" # Rack 3 moved session middleware to separate gem
gem "webrick" # Rack handler for Sidekiq Web monitor

group :development do
  gem "standard", ">= 1.35.1", require: false
  gem "rubocop", require: false
  gem "rspec", require: false
  gem "rspec-given", require: false
end
