source "https://rubygems.org"

gem "thor"
gem "nitty_mail", path: "../gem"
gem "ruby-progressbar"
gem "reverse_markdown"
gem "mail"
gem "activerecord", ">= 8.0", "< 9.0"
gem "sqlite3", ">= 2.1", "< 3.0"
gem "activesupport", ">= 8.0", "< 9.0"

group :development do
  gem "standard", ">= 1.35.1", require: false
  gem "rubocop", require: false
  gem "rspec", require: false
  gem "rspec-given", require: false
end
