inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - ".bundle/**/*"
    - "data/**/*"
    - "config/**/*"
    - "Gemfile.lock"
