# frozen_string_literal: true

source "https://rubygems.org"

gem "debug"
gem "dotenv"
gem "mail"
gem "net-imap", require: false
gem "net-pop", require: false
gem "net-smtp", require: false
gem "sequel"
gem "sqlite3"

# Linting
gem "rubocop", require: false
gem "standard", require: false
