# frozen_string_literal: true

source "https://rubygems.org"

gem "bigdecimal"
gem "debug"
gem "dotenv"
gem "mail"
gem "net-imap", require: false
gem "net-pop", require: false
gem "net-smtp", require: false
gem "ruby-progressbar"
gem "sequel"
gem "sqlite3"
gem "thor"

# Linting
gem "rubocop", require: false
gem "rubocop-sequel", require: false
gem "standard", require: false

# Testing (optional)
group :development, :test do
  gem "rspec"
  gem "rspec-given"
end
